<a href="https://colab.research.google.com/github/anujsanap25-nxtwave/Data_science_lab_SE_72/blob/main/practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
.print("Create a 3x3 square matrix and compute its determinant.")

Create a 3x3 square matrix and compute its determinant.


In [12]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([
    [3, 2, 3],
    [4, 2, 3],
    [2, 4, 4]
])

print("Original 3x3 Matrix:")
print(matrix)

print("\n--- Manual Determinant Calculation ---")

# Extract elements for clarity (matrix A = [[a,b,c], [d,e,f], [g,h,i]])
a, b, c = matrix[0,0], matrix[0,1], matrix[0,2]
d, e, f = matrix[1,0], matrix[1,1], matrix[1,2]
g, h, i = matrix[2,0], matrix[2,1], matrix[2,2]

# Formula for determinant of a 3x3 matrix (cofactor expansion along first row):
# det(A) = a * (e*i - f*h) - b * (d*i - f*g) + c * (d*h - e*g)

# Calculate the 2x2 determinants for each cofactor
minor_A = (e * i) - (f * h)
minor_B = (d * i) - (f * g)
minor_C = (d * h) - (e * g)

print(f"Minor for element {a} (top-left): ({e}*{i} - {f}*{h}) = {minor_A}")
print(f"Minor for element {b} (top-middle): ({d}*{i} - {f}*{g}) = {minor_B}")
print(f"Minor for element {c} (top-right): ({d}*{h} - {e}*{g}) = {minor_C}")

determinant_manual = a * minor_A - b * minor_B + c * minor_C

print(f"\nManually calculated determinant: {determinant_manual:.2f}")

# For verification (using NumPy's function - this part is just for comparison, not part of the manual calculation)
determinant_numpy = np.linalg.det(matrix)
print(f"NumPy's np.linalg.det result (for comparison): {determinant_numpy:.2f}")

Original 3x3 Matrix:
[[3 2 3]
 [4 2 3]
 [2 4 4]]

--- Manual Determinant Calculation ---
Minor for element 3 (top-left): (2*4 - 3*4) = -4
Minor for element 2 (top-middle): (4*4 - 3*2) = 10
Minor for element 3 (top-right): (4*4 - 2*2) = 12

Manually calculated determinant: 4.00
NumPy's np.linalg.det result (for comparison): 4.00


In [7]:
import numpy as np
A = np.array([[2,3],
              [4,5]])
B = np.array([10,20])

x,y = np.linalg.solve(A,B)
print(f"the solution is: x = {x:.2f}, y = {y:.2f}")

the solution is: x = 5.00, y = 0.00


In [3]:
print("Find the inverse of the matrix.")

Find the inverse of the matrix.


In [10]:
import numpy as np

matrix = np.array([
    [1,2,3],
    [0,1,4],
    [5,6,0]
])

print("Original 3*3 matrix: ")
print(matrix)

print("\n--- Manual Calculation of Inverse for a 3x3 Matrix ---")

# Extract elements for clarity
a, b, c = matrix[0,0], matrix[0,1], matrix[0,2]
d, e, f = matrix[1,0], matrix[1,1], matrix[1,2]
g, h, i = matrix[2,0], matrix[2,1], matrix[2,2]

# Step 1: Calculate the determinant of the matrix
determinant = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
print(f"Step 1: Determinant = {determinant:.2f}")

if determinant == 0:
    print("Error: The determinant is zero, so the matrix is singular and does not have an inverse.")
else:
    # Step 2: Calculate the Matrix of Minors
    M11 = e * i - f * h
    M12 = d * i - f * g
    M13 = d * h - e * g
    M21 = b * i - c * h
    M22 = a * i - c * g
    M23 = a * h - b * g
    M31 = b * f - c * e
    M32 = a * f - c * d
    M33 = a * e - b * d

    matrix_of_minors = np.array([
        [M11, M12, M13],
        [M21, M22, M23],
        [M31, M32, M33]
    ])
    print("\nStep 2: Matrix of Minors:\n", matrix_of_minors)

    # Step 3: Calculate the Matrix of Cofactors (apply checkerboard pattern of signs)
    C11, C12, C13 = M11, -M12, M13
    C21, C22, C23 = -M21, M22, -M23
    C31, C32, C33 = M31, -M32, M33

    matrix_of_cofactors = np.array([
        [C11, C12, C13],
        [C21, C22, C23],
        [C31, C32, C33]
    ])
    print("\nStep 3: Matrix of Cofactors:\n", matrix_of_cofactors)

    # Step 4: Calculate the Adjugate (or Adjoint) matrix (transpose of the Cofactor Matrix)
    adjugate_matrix = matrix_of_cofactors.transpose()
    print("\nStep 4: Adjugate Matrix:\n", adjugate_matrix)

    manual_inverse_matrix = (1 / determinant) * adjugate_matrix
    print("\nStep 5: Manually calculated Inverse of the matrix:\n", manual_inverse_matrix)



Original 3*3 matrix: 
[[1 2 3]
 [0 1 4]
 [5 6 0]]

--- Manual Calculation of Inverse for a 3x3 Matrix ---
Step 1: Determinant = 1.00

Step 2: Matrix of Minors:
 [[-24 -20  -5]
 [-18 -15  -4]
 [  5   4   1]]

Step 3: Matrix of Cofactors:
 [[-24  20  -5]
 [ 18 -15   4]
 [  5  -4   1]]

Step 4: Adjugate Matrix:
 [[-24  18   5]
 [ 20 -15  -4]
 [ -5   4   1]]

Step 5: Manually calculated Inverse of the matrix:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

For comparison, Inverse using np.linalg.inv:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [ ]:
print("Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20")

Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20


In [8]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [4,8,9]])

print("The 3*3 matrix is: ")
print(matrix)
a = matrix[0,0]
b = matrix[0,1]
c = matrix[0,2]
d = matrix[1,0]
e = matrix[1,1]
f = matrix[1,2]
g = matrix[2,0]
h = matrix[2,1]
i = matrix[2,2]
determinant_manual = a * ((e * i) - (f * h)) - b * ((d * i) - (f * g)) + c * ((d * h) - (e * g))
print(f"\nThe determinant of the matrix (manually calculated) is: {determinant_manual:.2f}")
# For comparison, using np.linalg.det
determinant_numpy = np.linalg.det(matrix)
print(f"The determinant of the matrix (using np.linalg.det) is: {determinant_numpy:.2f}")

The 3*3 matrix is: 
[[1 2 3]
 [4 5 6]
 [4 8 9]]

The determinant of the matrix (manually calculated) is: 9.00
The determinant of the matrix (using np.linalg.det) is: 9.00
